import type { Vendor } from "@ghostshift/shared";

export const vendorCatalog: Vendor[] = [
  {
    id: "orbit-browser",
    name: "Orbit Browser Cloud",
    category: "infra",
    lane: "browser",
    tagline: "Headless browser sessions for agent test and checkout flows.",
    payoutAddress: "casper-test:01-orbit",
    trialPriceMotes: 1_450_000_000,
    qualityScore: 94,
    reliability: 0.98,
    setupMinutes: 12,
    securityGrade: "A",
    supportsMcp: true,
    supportsX402: true,
    deliveryMode: "fresh",
    sampleArtifactUrl: "https://vendors.ghostshift.local/orbit/trial.json"
  },
  {
    id: "echo-render",
    name: "Echo Render",
    category: "infra",
    lane: "browser",
    tagline: "Cheaper browser automation with slow warm-up times.",
    payoutAddress: "casper-test:02-echo",
    trialPriceMotes: 1_100_000_000,
    qualityScore: 88,
    reliability: 0.8,
    setupMinutes: 25,
    securityGrade: "B",
    supportsMcp: true,
    supportsX402: false,
    deliveryMode: "stale",
    sampleArtifactUrl: "https://vendors.ghostshift.local/echo/trial.json"
  },
  {
    id: "tab-forge",
    name: "Tab Forge",
    category: "infra",
    lane: "browser",
    tagline: "Fast claims, broken trial artifacts.",
    payoutAddress: "casper-test:03-tabforge",
    trialPriceMotes: 1_550_000_000,
    qualityScore: 76,
    reliability: 0.72,
    setupMinutes: 10,
    securityGrade: "C",
    supportsMcp: false,
    supportsX402: true,
    deliveryMode: "malformed",
    sampleArtifactUrl: "https://vendors.ghostshift.local/tabforge/trial.json"
  },
  {
    id: "northstar-observatory",
    name: "Northstar Observatory",
    category: "infra",
    lane: "telemetry",
    tagline: "Low-latency observability tuned for agent fleets.",
    payoutAddress: "casper-test:04-northstar",
    trialPriceMotes: 1_250_000_000,
    qualityScore: 92,
    reliability: 0.97,
    setupMinutes: 18,
    securityGrade: "A",
    supportsMcp: true,
    supportsX402: true,
    deliveryMode: "fresh",
    sampleArtifactUrl: "https://vendors.ghostshift.local/northstar/trial.json"
  },
  {
    id: "quartz-trace",
    name: "Quartz Trace",
    category: "infra",
    lane: "telemetry",
    tagline: "Good pricing, laggy data export path.",
    payoutAddress: "casper-test:05-quartz",
    trialPriceMotes: 950_000_000,
    qualityScore: 84,
    reliability: 0.76,
    setupMinutes: 30,
    securityGrade: "B",
    supportsMcp: false,
    supportsX402: true,
    deliveryMode: "stale",
    sampleArtifactUrl: "https://vendors.ghostshift.local/quartz/trial.json"
  },
  {
    id: "blindspot-logs",
    name: "Blindspot Logs",
    category: "infra",
    lane: "telemetry",
    tagline: "Incomplete log payloads hidden behind strong marketing.",
    payoutAddress: "casper-test:06-blindspot",
    trialPriceMotes: 1_300_000_000,
    qualityScore: 72,
    reliability: 0.69,
    setupMinutes: 16,
    securityGrade: "C",
    supportsMcp: false,
    supportsX402: false,
    deliveryMode: "malformed",
    sampleArtifactUrl: "https://vendors.ghostshift.local/blindspot/trial.json"
  },
  {
    id: "vaultpass-cloud",
    name: "VaultPass Cloud",
    category: "infra",
    lane: "auth",
    tagline: "Managed auth, session keys, and passkey flows for agent products.",
    payoutAddress: "casper-test:07-vaultpass",
    trialPriceMotes: 1_500_000_000,
    qualityScore: 91,
    reliability: 0.96,
    setupMinutes: 16,
    securityGrade: "A+",
    supportsMcp: true,
    supportsX402: false,
    deliveryMode: "fresh",
    sampleArtifactUrl: "https://vendors.ghostshift.local/vaultpass/trial.json"
  },
  {
    id: "latchline-id",
    name: "Latchline ID",
    category: "infra",
    lane: "auth",
    tagline: "Budget identity layer with slower provisioning.",
    payoutAddress: "casper-test:08-latchline",
    trialPriceMotes: 1_200_000_000,
    qualityScore: 83,
    reliability: 0.79,
    setupMinutes: 28,
    securityGrade: "B",
    supportsMcp: false,
    supportsX402: true,
    deliveryMode: "stale",
    sampleArtifactUrl: "https://vendors.ghostshift.local/latchline/trial.json"
  },
  {
    id: "phantom-access",
    name: "Phantom Access",
    category: "infra",
    lane: "auth",
    tagline: "Shiny auth promises, incomplete setup guides.",
    payoutAddress: "casper-test:09-phantom",
    trialPriceMotes: 1_350_000_000,
    qualityScore: 71,
    reliability: 0.68,
    setupMinutes: 14,
    securityGrade: "C",
    supportsMcp: false,
    supportsX402: false,
    deliveryMode: "malformed",
    sampleArtifactUrl: "https://vendors.ghostshift.local/phantom/trial.json"
  },
  {
    id: "index-harbor",
    name: "Index Harbor",
    category: "infra",
    lane: "knowledge",
    tagline: "Knowledge indexing and retrieval for agent memory loops.",
    payoutAddress: "casper-test:10-index",
    trialPriceMotes: 1_600_000_000,
    qualityScore: 95,
    reliability: 0.98,
    setupMinutes: 14,
    securityGrade: "A",
    supportsMcp: true,
    supportsX402: true,
    deliveryMode: "fresh",
    sampleArtifactUrl: "https://vendors.ghostshift.local/index/trial.json"
  },
  {
    id: "dust-library",
    name: "Dust Library",
    category: "infra",
    lane: "knowledge",
    tagline: "Affordable retrieval with stale sync windows.",
    payoutAddress: "casper-test:11-dust",
    trialPriceMotes: 1_200_000_000,
    qualityScore: 82,
    reliability: 0.78,
    setupMinutes: 27,
    securityGrade: "B",
    supportsMcp: true,
    supportsX402: false,
    deliveryMode: "stale",
    sampleArtifactUrl: "https://vendors.ghostshift.local/dust/trial.json"
  },
  {
    id: "fog-retrieval",
    name: "Fog Retrieval",
    category: "infra",
    lane: "knowledge",
    tagline: "Broken document outputs dressed up as premium RAG.",
    payoutAddress: "casper-test:12-fog",
    trialPriceMotes: 1_550_000_000,
    qualityScore: 74,
    reliability: 0.7,
    setupMinutes: 11,
    securityGrade: "C",
    supportsMcp: false,
    supportsX402: true,
    deliveryMode: "malformed",
    sampleArtifactUrl: "https://vendors.ghostshift.local/fog/trial.json"
  }
];
